### ISSUE TITLE
No Numeric Text Field

### ISSUE THREAD

**Issue by saadurrehman-selectquote** [SelectQuoteLabs/SQForm#35] opened 2020-12-23 08:40 UTC
![image](https://user-images.githubusercontent.com/76514364/102977021-3f6a4380-4524-11eb-9512-89cd158e397a.png)
 there must be a numeric field which only allow numbers. i am facing this issue in zipcode field

**Comment by SeanGroff** [comment] 2020-12-23 16:28
@saadurrehman-selectquote 
Thank you for raising this issue. This is a duplicate of issue #18 
I'm going to close this issue because it's a duplicate issue. Please follow that issue thread and add to that conversation if needed. Thank you sir

**Closed by SeanGroff** 2020-12-23 16:28 UTC
