### ISSUE TITLE
Yup.boolean validation should also validate false value, as false is also a bool value.

### ISSUE THREAD

**Issue by azharsaeed951** [SelectQuoteLabs/SQForm#283] opened 2021-05-25 08:59 UTC
Here's a loom elaborating the issue:
Loom video link: https://www.loom.com/share/5262c0eeeefc49188beaa576fd5fd807

**Comment by codyarose** [comment] 2021-05-27 19:44
If I remember correctly, SQFormDropdown does not accept booleans as values in the options array because of validation issues, so I'm curious if you have errors in the console from this.

This may be a duplicate of #174

**Comment by azharsaeed951** [comment] 2021-05-28 11:59
Yeah. I've looked into #174 and it seems that this issue is a duplicate of that one. My bad. Thanks for the update.

**Closed** 2021-05-28 13:11 UTC
